apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: # can be define my user/creator no such predefine
    app: myap2
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        memory: "256Mi"
        cpu: "250m"
    ports:
      - containerPort: 80